name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "No tests yet — skipping"

  build_docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t tini3393/devops-lab-app:latest .

      - name: Push Docker image
        run: |
          docker push tini3393/devops-lab-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_docker
    steps:
      - name: Deploy placeholder
        run: |
          echo "Deployment simulated. Add SSH or cloud deploy later."
